### ISSUE TITLE
Dissolution / Buyout 

### ISSUE THREAD

**Issue by zeryx** [fractional-finance/frabric-protocol#5]
https://github.com/fractional-finance/frabric-protocol/blob/93f1721200f9ed95a6b30ab3142c2b0b23b5d22c/contracts/asset/Asset.sol#L96-L102

This looks good, but one thing I realized; we don't verify that the sender actually has the funds necessary to buy out the Asset!
This proposal type should require Y*X $SC tokens to be sent to it, which would be held in escrow until the voting round is complete, where Y is the proposed price per token of the buy out, and X is the total amount of tokens distributed (including tokens locked for sale)

**Comment by VecDequer** [comment]
This definitely isn't a bug. The funds are required when the dissolution is passed via:
```
    } else if (_dissolution[id].purchaseAmount != 0) {
              _distribute(_dissolution[id].purchaser, _dissolution[id].purchaseAmount);
```

You are correct they're not required at the time of proposal though, and a flow change may be optimal to reduce spam/ensure expectations.

**Comment by zeryx** [comment]
Oh nice I didn't see that, yes the intent was to ensure an automatic payout in the event that a buyout proposal passes; for now it's the only proposal type that requires funds (beyond the gas fees) to be paid - however as we test out the system we might want to extend the proposal mechanism to require some kind of "proposal fee" to avoid spam.

**Comment by VecDequer** [comment]
Sure. We can definitely move this flow.
